YOUR_DBT_PROJECT:
  target: dev
  outputs:
    local:
      dataset: YOUR_DATASET
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: service-account
      keyfile: tempkey.json
      priority: interactive
      project: YOUR_PROJECT
      threads: 4
      type: bigquery
    dev:
      dataset: YOUR_DATASET
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: YOUR_PROJECT
      threads: 4
      type: bigquery